theme = "solarized-dark"
icons = "awesome"
[[block]]
block = "memory"
display_type = "memory"
format_mem = "RAM: {mem_used_percents}"
format_swap = "SWAP: {swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
 16
[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT1"
